# PM Agent Application Configuration
# Centralized configuration for all components

app:
  name: "PM Agent"
  version: "1.0.0"
  environment: "development"  # development, staging, production

# Model configurations - centralize all model names
models:
  # Default models by use case
  default_chat: "gpt-4.1-2025-04-14"
  default_nano: "gpt-4.1-nano-2025-04-14"
  
  # Specific agent models
  review_classifier: "gpt-4.1-nano-2025-04-14"

  bug_bot: "gpt-4.1-2025-04-14"
  bug_approval_judge: "gpt-4.1-2025-04-14"
    
  # Feature Research Bot models
  feature_research_bot: "gpt-4.1-nano-2025-04-14"
  feature_research_planner: "gpt-4.1-2025-04-14"
  feature_web_researcher: "gpt-4.1-2025-04-14"  # Needs stronger model for web search
  feature_competitor_analyst: "gpt-4.1-nano-2025-04-14"
  feature_spec_writer: "gpt-4.1-2025-04-14"

  approval_executor: "gpt-4.1-2025-04-14"

# Service URLs and connections
services:
  mcp:
    youtrack_url: "http://mcp_youtrack:8002/mcp"
    timeout_seconds: 30
    
  database:
    # Use environment variables for sensitive data
    url_env_var: "DATABASE_URL"
    pool_size: 10
    timeout_seconds: 30
    
  langfuse:
    project_name: "pm-agent"
    enabled: true
    trace_all_agents: true

# Default project settings
youtrack_projects:
  default: "INT"
  supported:
    - "INT"
    - "DEMO"

# Default competitor analysis configuration
competitors:
  - "Udemy"
  - "Coursera"
  - "edX"
  - "DataCamp"
  - "Pluralsight"
  - "Skillshare"

# Agent-specific configurations
agents:
  bug_bot:
    default_project: "INT"
    timeout_seconds: 300
    max_retries: 3
    
  review_classifier:
    batch_size: 100
    timeout_seconds: 120
    confidence_threshold: 0.8
    
  bug_approval_judge:
    timeout_seconds: 30
    fallback_requires_approval: true
    fallback_risk_level: "MEDIUM"
    
  feature_research_bot:
    timeout_seconds: 600  # Longer timeout for web research
    max_search_queries: 10
    max_competitors_to_analyze: 5
    require_citations: true
    min_evidence_per_claim: 1

# Integration settings
integrations:
  slack:
    enabled: true
    socket_mode: true
    default_channel: "C0853BCBX3R" # "approvals"
    channel_by_risk:
      HIGH: "C0853BCBX3R" # "critical-approvals"
      MEDIUM: "C0853BCBX3R" # "approvals"
      LOW: "C0853BCBX3R" # "approvals"
    timeout_seconds: 10
    reviewers_whitelists:
      - "U05KBUG2SKX"
      - "U01234567"  # Replace with actual Slack user IDs
      - "U98765432"
    
  youtrack:
    default_project: "INT"
    timeout_seconds: 60
    max_retries: 3

# Guardrails configuration
guardrails:
  enabled: true
  bug_submission:
    enabled: true
    slack_notifications: true
    timeout_seconds: 45
    
  approval:
    default_expiration_hours: 48
    expiration_by_risk:
      HIGH: 24
      MEDIUM: 48
      LOW: 72
    auto_expire_enabled: true
    check_interval_hours: 6

# Queue-based background services (replaces polling)
services_config:
  queue:
    # Redis connection
    redis_url: "redis://redis:6379"
    redis_db: 0
    
    # Worker configuration
    max_workers: 2
    max_jobs_per_worker: 10
    job_timeout_seconds: 300
    
    # Retry logic
    max_retries: 3
    retry_delay_seconds: 60
    retry_backoff_multiplier: 2.0
    
    # Queue names by priority
    high_priority_queue: "approvals:high"
    normal_queue: "approvals:normal" 
    low_priority_queue: "approvals:low"
    dead_letter_queue: "approvals:dlq"
    
    # Queue routing by risk level
    queue_by_risk:
      HIGH: "approvals:high"
      MEDIUM: "approvals:normal"
      LOW: "approvals:low"

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  
  # What to log
  log_agent_calls: true
  log_mcp_calls: true
  log_database_queries: false
  log_slack_messages: true
  log_approvals: true
  
  # Metrics and monitoring
  enable_metrics: true
  langfuse_tracing: true

# Development and testing settings
development:
  debug: true
  
  # Mock services for testing
  mock_slack: false
  mock_mcp: false
  mock_database: false
  
  # Bypass features for development
  bypass_guardrails: false
  auto_approve_all: false
  
  # Test data
  use_test_data: false
  dry_run_mode: false

# Performance tuning
performance:
  # Connection pooling
  max_concurrent_agents: 5
  max_db_connections: 20
  
  # Caching
  cache_prompts: true
  cache_ttl_seconds: 3600
  
  # Rate limiting
  max_requests_per_minute: 100

# Security settings
security:
  # API keys via environment variables
  required_env_vars:
    - "OPENAI_API_KEY"
    - "SLACK_BOT_TOKEN"
    - "SLACK_APP_TOKEN"
    - "DATABASE_URL"
    
  # Optional env vars
  optional_env_vars:
    - "LANGFUSE_SECRET_KEY"
    - "LANGFUSE_PUBLIC_KEY"
    
  # Validation
  validate_inputs: true
  sanitize_outputs: true