hypotheses:
- description: Users will adopt and frequently use course progress reset to revisit
    and master content.
  id: H1
- description: Gamification and social competition features will increase daily active
    use and retention rates.
  id: H2
- description: Advanced search within courses will reduce user frustration and increase
    lesson completion rates.
  id: H3
personas:
- background: '33-year-old accountant in Samara planning a switch to analytics. Seeks
    beginner-friendly, structured

    paths and relies on recommendations and open lessons to trial before paying. Needs
    flexible pacing

    and clear progress signals.

    '
  id: svetlana
  name: Svetlana Orlova
- background: '19-year-old first-year CS student in Perm. Competitive, studies almost
    every day and proudly keeps

    a long learning streak. Races peers on the knowledge leaderboard and seeks challenging
    tasks to

    keep climbing. Shares badges and milestones in class chats.'
  id: nikita
  name: Nikita Orlov
- background: '21-year-old 3rd-year economics student in Novosibirsk. Studies on mobile
    during commutes and evenings,

    prefers self-paced courses with practice. Wants certificates to add to her CV.
    Price sensitive; buys on

    discounts. Uses wishlist for price drops.

    '
  id: nastya
  name: Anastasia Moroz
phase_config:
  closure:
    max_follow_ups: 0
  converge:
    force_tradeoffs: true
  diverge:
    max_follow_ups: 2
  warmup:
    max_follow_ups: 1
product:
  description: CourseCraft is a mobile-focused online learning platform that empowers
    users to repeat courses, track achievements, and connect with peers, all with
    intuitive controls and robust progress management. Designed for learners seeking
    structure, motivation, and flexibility, it delivers community features, progress
    resets, and advanced in-app searching to make continuous skill growth frictionless.
  name: CourseCraft
questions: !!python/object:pipeline_models.ResearchQuestions
  __dict__:
    closure:
    - Are there any aspects of this platform or its features that would prevent you
      from using it, even if the price or content were appealing?
    - How likely are you to recommend CourseCraft to a friend or peer if it delivers
      on these features?
    - What are the biggest risks, uncertainties, or doubts you have about CourseCraft
      or its approach to learning?
    converge:
    - "If you could only have one of the following features\u2014course reset, gamification/leaderboards,\
      \ or advanced in-app search\u2014which would you choose and why?"
    - How likely would you be to pay for or subscribe to a mobile learning platform
      with these features if the price was right for your budget?
    - "How does this concept compare to other online learning tools or platforms you\u2019\
      ve used\u2014what stands out as better or worse?"
    diverge:
    - !!python/object:pipeline_models.DivergeQuestion
      __dict__:
        covers:
        - H1
        rationale: This question explores initial reactions and potential use cases
          of the course reset feature, directly addressing whether repeat learning
          is a valued workflow.
        text: Imagine a mobile platform where you can reset your progress on any course
          and start over at any time. What are your thoughts on this feature? How
          would you see yourself using it, if at all?
      __pydantic_extra__: null
      __pydantic_fields_set__: !!set
        covers: null
        rationale: null
        text: null
      __pydantic_private__: null
    - !!python/object:pipeline_models.DivergeQuestion
      __dict__:
        covers:
        - H2
        rationale: This question uncovers the attractiveness and motivational impact
          of gamification and competition features for different user types.
        text: How do you feel about having leaderboards, badges, and competitive challenges
          as part of your learning experience? Would these features affect your motivation
          or daily participation?
      __pydantic_extra__: null
      __pydantic_fields_set__: !!set
        covers: null
        rationale: null
        text: null
      __pydantic_private__: null
    - !!python/object:pipeline_models.DivergeQuestion
      __dict__:
        covers:
        - H3
        rationale: This probes into perceived value and practical utility of advanced
          in-app search, testing if it addresses real frustrations and accelerates
          learning.
        text: If you could search for specific topics or keywords within and across
          courses, how useful do you think that would be for your learning? Can you
          recall moments when such a feature would have helped you in the past?
      __pydantic_extra__: null
      __pydantic_fields_set__: !!set
        covers: null
        rationale: null
        text: null
      __pydantic_private__: null
    - !!python/object:pipeline_models.DivergeQuestion
      __dict__:
        covers:
        - H2
        rationale: Broadens exploration of social features beyond pure competition
          to capture the importance and desired forms of peer interaction.
        text: What role does community or social interaction play in your online learning
          experience, and in what ways do you seek or avoid peer engagement?
      __pydantic_extra__: null
      __pydantic_fields_set__: !!set
        covers: null
        rationale: null
        text: null
      __pydantic_private__: null
    warmup:
    - Can you tell us about your current methods and platforms for learning new skills
      or topics?
    - What are some of the biggest challenges or frustrations you've faced with online
      courses or self-study?
  __pydantic_extra__: null
  __pydantic_fields_set__: !!set
    closure: null
    converge: null
    diverge: null
    warmup: null
  __pydantic_private__: null
